version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - product-service

  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - database

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
